### ISSUE TITLE
部署了midjourney-proxy 以及  wechat-midjourney 怎么才能生成图片

### ISSUE THREAD

**Issue by lovecodeyou** [novicezk/wechat-midjourney#4]
midjourney-proxy的接口通了mj/trigger/submit，可以在discord的频道看到生成的图片

wechat-midjourney 扫码生成了，需要怎么才能收到midjourney-proxy的信息呢？我看README.md没写怎么用

![image](https://user-images.githubusercontent.com/38997988/236689064-e4b1eff5-89f6-442a-8a31-586d19a344d6.png)

**Comment by novicezk** [comment]
不用@微信，群里直接发 /help 会回复使用说明

**Comment by lovecodeyou** [comment]
解决了，是我没配mj.notify-hook参数导致一直微信没回调通知

**Comment by ghost** [comment]
> 解决了，是我没配mj.notify-hook参数导致一直微信没回调通知

mj.notify-hook参数这个怎么配呀
