### ISSUE TITLE
about notify

### ISSUE THREAD

**Issue by joyhope** [novicezk/wechat-midjourney#5]
/help 可以工作, /imagine 也可以工作.  但是无法得到 /notify 的事件通知, 执行结果不知道,  绘画完成不知道. 

我哪里设置还有问题?

**Comment by joyhope** [comment]
看了代码, 这个/notify 是 midjourney-proxy推送过来的, 这样应该和 设置有关了.

**Comment by joyhope** [comment]
mj.notify-hook 的参数设置  要包含 /notify 吗?

**Comment by KzWillbeBetter** [comment]
这一步怎么解决
